version: "3"

services:
  web:
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pycon
      SECRET_KEY: "django-insecure-gijk%bb1-ss)p92h0(-ai2l4!j44vsjs+4ez+^v-f=k!&dtwh8"
      EXTRA_ALLOWED_HOSTS: "localhost"
      PRETALX_TOKEN: "${PRETALX_TOKEN}"
    volumes:
      - .:/code
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pycon
    ports:
      - "5433:5432"
volumes:
  postgres_data:
