version: "3"

services:
  web:
    build: .
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - db:/app/db
    ports:
      - "8000:8000"
    tty: true
volumes:
  db:

