# fly.toml app configuration file generated for pycon-cz-prod on 2023-05-29T16:52:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pycon-cz-prod"
primary_region = "ams"

[deploy]
  release_command = "bash -c \"npm clean-install && npm run build && python manage.py migrate\""

[env]
  PORT = "8000"
  SENTRY_ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static/"

[mounts]
  source="django_images_data"
  destination="/code/data"

[regions]
allow = ["ams"]
