name: Buid
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Build test image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: vars
        name: Compute short SHA for SENTRY_RELEASE
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
